### ISSUE TITLE
Publish / Subscribe issue

### ISSUE THREAD

**Issue by macpie** [basho/enm#17]
Hi,

I am having an issue with the pub/sub model where I am trying to publish a message but it is not received by the subscriber.

The subscriber is a simple gen_server that subscribe for topics (topicA, topicB, topicC) it also has a publisher all stored in the `state`.

When I try to publish from my test module, the message is not received but when I do it via the `gen_server` (using `pid(0, 82, 0) ! {pub, <<"topicA">>}.` ) it works fine.

The weirdness happens when I am not creating a publisher in my subscriber module anymore and decide to add a `timer:sleep(1000)` in my test module suddenly it works!

I must be doing something really wrong but I cannot tell what.

Thanks

```erlang
-module(subscriber).
-behaviour(gen_server).
-define(SERVER, ?MODULE).

%% ------------------------------------------------------------------
%% API Function Exports
%% ------------------------------------------------------------------
-export([start_link/0]).

%% ------------------------------------------------------------------
%% gen_server Function Exports
%% ------------------------------------------------------------------
-export([
    init/1
    ,handle_call/3
    ,handle_cast/2
    ,handle_info/2
    ,terminate/2
    ,code_change/3
]).

-record(state, {pub, subs}).

-define(TOPICS, [<<"topicA">>, <<"topicB">>, <<"topicC">>]).

%% ------------------------------------------------------------------
%% API Function Definitions
%% ------------------------------------------------------------------
start_link() ->
    gen_server:start_link({'local', ?SERVER}, ?MODULE, [], []).

%% ------------------------------------------------------------------
%% gen_server Function Definitions
%% ------------------------------------------------------------------
init(_Args) ->
    {'ok', Connect} = application:get_env('test', 'enm_connect'),
    Subs =
        lists:foldl(
            fun(Topic, Acc) ->
                {'ok', Sub} = enm:sub([{'connect', Connect}, {'subscribe', Topic}]),
                lager:debug("subscribed to ~p via ~p, ~p", [Topic, Connect, Sub]),
                [Sub|Acc]
            end
            ,[]
            ,?TOPICS
        ),
    {'ok', Bind} = application:get_env('test', 'enm_bind'),
    {'ok', Pub} = enm:pub([{'bind', Bind}]),
    % Pub = ok,
    lager:debug("ready to publish @ ~p via ~p", [Bind, Pub]),
    {'ok', #state{pub=Pub, subs=Subs}}.


handle_call(pub, _From, #state{pub=Pub}=State) ->
    {'reply', Pub, State};
handle_call(_Request, _From, State) ->
    {'reply', 'ok', State}.

handle_cast(_Msg, State) ->
    {'noreply', State}.

handle_info({'nnsub', _Sub, <<"topicA", Msg/binary>>}, State) ->
    Map = utils:unpack(Msg),
    lager:debug("~p", [Map]),
    {'noreply', State};
handle_info({'nnsub', _Sub, <<"topicB", Msg/binary>>}, State) ->
    Map = utils:unpack(Msg),
    lager:debug("~p", [Map]),
    {'noreply', State};
handle_info({'nnsub', _Sub, <<"topicC", Msg/binary>>}, State) ->
    Map = utils:unpack(Msg),
    lager:debug("~p", [Map]),
    {'noreply', State};
handle_info({'pub', Topic}, #state{pub=Pub}=State) ->
    lager:debug("topic: ~p", [Topic]),
    Map = #{<<"key">> => <<"value">>},
    Packed = utils:pack(Map),
    Msg = <<Topic/binary, Packed/binary>>,
    lager:debug("message: ~p", [Msg]),
    'ok' = enm:send(Pub, Msg),
    lager:debug("message sent"),
    {'noreply', State};
handle_info(_Info, State) ->
    lager:debug("~p", [_Info]),
    {'noreply', State}.

terminate(_Reason, _State) ->
    'ok'.

code_change(_OldVsn, State, _Extra) ->
    {'ok', State}.
```

and the test module:

```erlang
-module(test).

-export([p/0, publish/1]).

%%--------------------------------------------------------------------
%% @public
%%--------------------------------------------------------------------
p() ->
    ?MODULE:publish(<<"topicA">>).

publish(Topic) ->
    {'ok', Pub} = enm:pub([{'bind', "tcp://*:11000"}]),
    Map = #{<<"key">> => <<"value">>},
    Packed = utils:pack(Map),
    Msg = <<Topic/binary, Packed/binary>>,
    % timer:sleep(1000),
    'ok' = enm:send(Pub, Msg),
    enm:close(Pub),
    lager:debug("message sent").
```

**Comment by vinoski** [comment]
Thanks for supplying this level of detail. I'll look into the problem.

**Comment by macpie** [comment]
Sure thing, I guess I can even add more:
```erlang
{enm_connect, "tcp://localhost:11000"}
{enm_bind, "tcp://*:11000"}
```

And after more testing, this works:
```erlang
pid(0, 86, 0) ! {'nnsub', 'undef', <<"topicA", (utils:pack(#{"key" => "value"}))/binary>>}.
```
_where pid is the subscriber's pid_

Thank you for looking into it.

**Comment by vinoski** [comment]
I spent a good bit of time in the debugger verifying enm's behavior and tracing nanomsg's behavior, and everything looks just right. This is what's happening:

 * When you open your subscriber sockets in the gen_server, they attempt to connect. When you open the publisher socket in the gen_server shortly thereafter, the subscribers connect and so by the time you send a message through the gen_server, all connections are stable and the message goes through.

 * If you don't open a publisher socket in the gen_server, the subscribers keep trying to connect according to the nanomsg `NN_RECONNECT_IVL` (reconnect interval) option on the socket, which defaults to 100ms. If you try to send a message via `test:p()`, which opens a publisher socket, sends a message on it, then closes it, everything occurs before any subscribers have a chance to connect, so they never see the message.

 * When you add a 1 second sleep to `test:p()` it gives the subscribers time to connect, so they see the message.

 * If you reduce your sleep time in `test:p()` from 1000ms to 100ms, it means you'll be waiting for the default reconnect interval, and the message will still get through. But if you drop that sleep time any lower, the message is likely to get dropped.

There's currently no option in `enm` that lets you set the reconnect interval on a socket (or the max reconnect interval `NN_RECONNECT_IVL_MAX`, but that's not involved here). If you'd like to be able to set a shorter reconnect time, I could easily that option; just let me know.

**Comment by macpie** [comment]
Thank you, this is really helpful. I knew there was something with timing but I would not have guessed that. I don't think I will need to change the interval just knowing about it should fix my issue (mentioning it in the doc could be good tho).

I have one last question for you: Is it possible to use the same socket (url/port) for different types (survey and pub/sub for ex)?

**Comment by vinoski** [comment]
No, using a socket for multiple protocols is not possible. A socket is tied to a specific protocol, as that's what the [underlying nanomsg libraries provide](http://nanomsg.org/v0.8/nn_socket.3.html).

I'll look into adding something to the doc about the reconnect interval, and even though I'm now closing this issue I've also decided to add options for specifying `NN_RECONNECT_IVL` and `NN_RECONNECT_IVL_MAX` anyway, since even though you don't need them, others might.

**Comment by macpie** [comment]
Yes, @vinoski thank you very much for your help.
