### ISSUE TITLE
Compilation difficulties on Windows 10

### ISSUE THREAD

**Issue by onnoowl** [basho/enm#19]
Hi,

I have little experience with C or Windows, but I'm using :enm as a dependency for an Elixir project, and I wanted to make sure my project compiled cross platform, but it won't get past enm when compiling on windows.

This is the error I get:
```
$ mix compile
==> enm (compile)
'c_src' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Command [compile] failed!
** (Mix) Could not compile dependency :enm, "escript.exe "c:/Users/Stuart/.mix/rebar" compile skip_deps=true deps_dir="c:/Users/Stuart/Documents/velexir_test/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile enm", update it with "mix deps.update enm" or clean it with "mix deps.clean enm"
```

I currently have Erlang/OTP 18, and Elixir 1.3.2.
I also attempted to use compile from Git Bash as a light-weight way to make the environment more Unix like.

What does it take to get enm up and running on Windows? Or am I doing something silly?
Thanks in advanced.

**Comment by vinoski** [comment]
This is just a guess, as I have no access to Windows. In [rebar.config](https://github.com/basho/enm/blob/master/rebar.config) on lines 12 and 14 try changing this:

```
{pre_hooks, [{compile, "c_src/build_deps.sh"}]}.

{post_hooks, [{clean, "c_src/build_deps.sh clean"}]}.```

to this:

```
{pre_hooks, [{compile, "./c_src/build_deps.sh"}]}.

{post_hooks, [{clean, "./c_src/build_deps.sh clean"}]}.```

If that works I can commit the fix.

**Comment by onnoowl** [comment]
Thanks so much for the quick reply!

I made the change, but now it says `'.' is not recognized as an internal or external command`. It seems it stops at the `/`. I tried replacing with backslashes just for kicks, and it didn't work.

I guess this is in no way an issue with your library, and more of a problem with getting rebar happy on windows. Any guess though as to what I could do?

**Comment by vinoski** [comment]
Did you use double backslashes, as in `{pre_hooks, [{compile, "c_src\\build_deps.sh"}]}.`?

I think there's a problem with the shell path, but there's likely also a problem with the environment not knowing what `build_deps.sh` is or how to run it. Since this is Windows 10, have you considered installing the [bash shell for Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) and trying to see if it can serve as a better environment for building `enm`?

**Comment by onnoowl** [comment]
Ah, no I didn't do double backslashes. Thanks. It fixed the issue, but then progresses on to say cl.exe is not a command. I thought Git Bash would be sufficient for a light weight dev environment, but I guess I need more tooling.

Thanks for the bash shell for windows tip! I didn't realize that existed, it looks nice. I installed it and tried to install erlang, but I keep getting crash dumps... It appears to be a none issue with bash for windows, but there are work-arounds.

Thanks so much for your assistance! I imagine once I get the windows-bash Ubuntu environment set up I'll no problems.
